### ISSUE TITLE
fordidden

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#11]
هردو فعال هستند.ولی باز هم خطای forbidden میده.

**Comment by sadeghesfahani** [comment]
https://github.com/sadeghesfahani/e-commerce/issues/9

این ایشو رو باز کردم اونجا بحث رو دنبال کنیم.

**Comment by ali-sj** [comment]
![1](https://user-images.githubusercontent.com/104249338/188285821-31e7008f-81a7-498e-8a7a-eb2f0507dfac.png)
![2](https://user-images.githubusercontent.com/104249338/188285824-5d70c3ea-2325-45be-9e6c-1ce2106e4041.png)
