### ISSUE TITLE
عدم دسترسی به سبد خرید

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#13]
سلاموخسته نباشید
هنگام واکشی سبد خرید به اررور 401 یرمیخورم
useEffect(()=>{
        console.log(auth.value.token);
        
        axios.get('http://localhost:8000/store/temporary_basket',{headers:{
            'Authorization': `Token${auth.value.token}`,
            'Content-Type': 'application/json'

        }})
        .then((res)=>console.log(res)
        )
        
    
    },[])

**Comment by sadeghesfahani** [comment]
در دادن توکن توی هدر باید بین Token و توکنتون یک اسپیس باشه.

**Comment by ali-sj** [comment]
بله مرسی درست شد
