### ISSUE TITLE
اند پوینت کامنت

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#14]
برای ارسال نظر برای هر محصول نیاز به یک اندپوینت برای کامنت ها دارم.

**Comment by sadeghesfahani** [comment]
برای دیدن مستندات [اینجا ](https://github.com/sadeghesfahani/e-commerce/wiki/%D9%85%D8%B3%D8%AA%D9%86%D8%AF%D8%A7%D8%AA#%D9%86%D8%B8%D8%B1%D8%A7%D8%AA)کلیک کنید
