### ISSUE TITLE
گرفتن تمام برند های یک دسته بندی

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#16]
سلام.نیاز دارم هنگام getکردن تمام دسته بندی ها،تمام برند های موجود در دسته بندی ها در رسپانس موجود باشد.ممنون از پاسخگویی🙏

**Comment by sadeghesfahani** [comment]
به منظور دریافت برند ها متغییر گت brand را برابر True قرار دهید توجه کنید که T باید بزرگ باشد

```
http://localhost:8000/store/category/?brand=True

```

**Comment by ali-sj** [comment]
انجام شد ولی یرند ها در ریسپانس ارسال نمیشود.

**Comment by sadeghesfahani** [comment]
دوباره بیلد بگیرید برای منم بدون بیلد کار نکرد
