### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#18]
سلام هنگام بیلد کردن این ارور رو دریافت میکنمودلیلش چی میتونه باشه؟
![error-build](https://user-images.githubusercontent.com/104249338/191085809-f1841aad-34c5-4c40-a79c-41ff9924e309.png)

**Comment by sadeghesfahani** [comment]
فیلتر شکن رو روشن کنید یا از دی ان اس های [شکن ](https://shecan.ir/)استفاده کنید.
