### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#20]
سلام خسته نباشید،هنگام ذخیره ادرس خطای کد 500میفرسته.

**Comment by sadeghesfahani** [comment]
سلام لطفا payload رو بفرستید

**Comment by ali-sj** [comment]
![Uploading IMG_۲۰۲۲۱۱۱۶_۱۵۵۳۲۵.jpg…]()

**Comment by sadeghesfahani** [comment]
تصویر درست آپلود نشده

**Comment by sadeghesfahani** [comment]
مشکل حل شد؟

**Comment by ali-sj** [comment]
سپاس ازشما،بله مشکل حل شد.
