### ISSUE TITLE
when run sudo docker-compose up --build  get an error :

### ISSUE THREAD

**Issue by Noahmpr** [sadeghesfahani/e-commerce#21]
This error 
Building ecommerce
Sending build context to Docker daemon  279.6kB
Step 1/11 : FROM python:3.8
 ---> 900972ffeecd
Step 2/11 : RUN apt-get update 	&& apt-get install -y --no-install-recommends 	postgresql-client 	&& rm -rf /var/lib/apt/lists/*
 ---> Running in a20ff4626b24
Err:1 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package postgresql-client
The command '/bin/sh -c apt-get update 	&& apt-get install -y --no-install-recommends 	postgresql-client 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'ecommerce' failed to build : Build failed

**Comment by sadeghesfahani** [comment]
مشکل از نتورک و داکر شماست. با چندین تست متوالی با این مشکل مواجه نشدم.
