### ISSUE TITLE
دسترسی به اطلاعات کاربر

### ISSUE THREAD

**Issue by mamad-dehghan** [sadeghesfahani/e-commerce#5]
کاربر ادمین باید بتواند به (بعضی از) اطلاعات کاربر دسترسی داشته باشد

**Comment by sadeghesfahani** [comment]
کامیت جدید برای رفع این مشکل انجام شد. لطفا در صورت کامل بودن کامیت و رفع تمام نیاز ها اعلان نمایید در غیر این صورت موارد مورد نیاز رو اعلان نمایید. با تشکر

**Comment by sadeghesfahani** [comment]
با تشکر از همکاری شما این فیچر با موفقیت اضافه شد
