### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#7]
سلام،نمیدونم چرا وقتی ریکوئست میزنم،ریکوئستم نمیاد سمت بک اصلا

**Comment by sadeghesfahani** [comment]
سلام لطفا جزئیات بیشتری رو اینجا به اشتراک بذارید تا بتونیم روش کار کنیم.
۱- از چه تکنولوژی فرانتی استفاده می کنید.
۲- از فچ استفاده می کنید یا اکسیوس یا ریداکس کوئری.
۳- کدی که دارید باهاش به بک اند درخواست میزنید رو هم بذارید.

**Comment by ali-sj** [comment]
از ری اکت استفاده میکنم.درخواست ها رو هم با axiosمیزنم.
  const submitHandler=async()=>{
        try{
                const response=await axios.post('http://localhost:8000/user/register',userInfo)
                console.log(response)
                navigate('/')
                setLogin(true)
                
        }
        catch{
            console.log('error');
            
        }
که userInfo اطلاعات یوزر هست.

**Comment by ali-sj** [comment]
از ری اکت استفاده میکنم درخواست هارو هم با axiosمیزنم.
  const submitHandler=async()=>{
        try{
                const response=await axios.post('http://localhost:8000/user/register',userInfo)
                console.log(response)
                navigate('/')
                setLogin(true)
                
        }
        catch{
            console.log('error');
            
        }

**Comment by ali-sj** [comment]
![Screenshot 2022-09-02 143413](https://user-images.githubusercontent.com/104249338/188226438-a475b34c-3e55-47b5-b20d-db3d2ff5bf92.png)


این هم cmdبک اند

**Comment by sadeghesfahani** [comment]
مشکل بر طرف شد. لطفا توجه داشته باشید برای تمامی رکوئست های پست در آخر آدرس / قرار دهید. البته این مشکل شما ربطی به این موضوع نداره ولی برای اینکه در آینده به مشکل نخورید بیان شد.

**Comment by ali-sj** [comment]
سپاس مشکل حل شد.ولی الان هنگام ثبت نام توکن داخل responseوجود ندارد

**Comment by sadeghesfahani** [comment]
یه ایشو جدید باز کنید این رو درست کنم براتون.
