### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by ali-sj** [sadeghesfahani/e-commerce#9]
وقتی به یک user برای دسترسی به اطلاعات همه کاربران permissionداده میشه باز هم خطای forbiddenمیده.
توکن توی هدر ارسال میشه
  axios.get('http://localhost:8000/user/get_all_users/',{headers:{
    Authorization: user.token
  }})
  .then((res)=>{console.log(res);
  })

**Comment by sadeghesfahani** [comment]
چطوری به یوزر پرمیشن کافی دادید؟

**Comment by ali-sj** [comment]
از پنل ادمین به کاربر پرمیشنview user دادم

**Comment by sadeghesfahani** [comment]
is_superuser
is_stuff

این هارو اکتیو کنید

**Comment by sadeghesfahani** [comment]
لطفا اطلاعات یوزرتون رو در پنل ادمین به صورت عکس بفرستید تا بررسی کنیم چه مشکلی در تعریف یوزر هست، من کد هارو دیدم مشکل از داخل کد نیست، پرمیشن به درستی به یوزر داده نشده. بیایید ایراد رو پیدا کنیم.

**Comment by ali-sj** [comment]
![1](https://user-images.githubusercontent.com/104249338/188285453-857120d7-2861-447b-98b5-30d2f55a741e.png)
![2](https://user-images.githubusercontent.com/104249338/188285458-53371c59-2bcc-4db9-bff5-291262e2101e.png)

**Comment by ali-sj** [comment]
![1](https://user-images.githubusercontent.com/104249338/188285854-9c04d0c8-6797-46f0-89d
![2](https://user-images.githubusercontent.com/104249338/188285855-00ed3df8-3c63-4a60-8cfd-314808b86af9.png)
3-8ad1bc685a69.png)

**Comment by ali-sj** [comment]
![1](https://user-images.githubusercontent.com/104249338/188285868-4c1015e1-fc33-4d1e-9cf1-369a07bd9a74.png)
![2](https://user-images.githubusercontent.com/104249338/188285871-12b9e600-4ebc-4ff0-a083-9097e2ef55e2.png)

**Comment by sadeghesfahani** [comment]
لطفا در این بخش
user/views.py

لاین ۶۵ و ۶۶ یه اینتر بزنید این رو وارد کنید.

`print(request.user.__dict__)`

بعد دوباره درخواست بزنید، ببینید اطلاعات یوزر مد نظرتون درسته یا نه.

چند تا مشکل میتونه اینجا رخ داده باشه:
۱- توکن یوزر اشتباه رو دارید میدید
۲- درست پول نمیکنید ریپازیتوری رو، از این دستور استفاده کنید
git pull origin master

۳- از قبل از تغییر این بخش شما تا الان کانتینر رو بیلد نکردید.


لطفا اگر مشکل با این موارد حل نشد نتیجه اون لاینی که اضافه کردید رو اینجا بذارید.

**Comment by sadeghesfahani** [comment]
یک مورد دیگه ای که احتمالا ممکنه توش ایراد وجود داشته باشه این هست که شما نوشتید:
`Authorization: user.token`

در صورتی که باید باشه:
`Authorization: "Token " + user.token `
